use crate::ir::{AggregationKind, Forest, MissingDirection, Node, Operator, PostTransform, SplitKind};
use anyhow::Result;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

/// Generate a standalone Rust source file from the given forest.
///
/// The output is a single module containing:
/// - A `bitset_contains` helper (only if categorical splits are present)
/// - A `Model` unit struct
/// - `Model::predict(&self, features: &[f32]) -> f32`
/// - One `#[inline(always)]` tree function per tree in the forest
pub fn generate(forest: &Forest) -> Result<String> {
    if forest.trees.is_empty() {
        anyhow::bail!("Cannot generate code for an empty forest (0 trees).");
    }

    // --- Conditional: bitset helper (emitted once at module scope) ---
    let needs_bitset = forest.trees.iter().any(|t| has_categorical(&t.root));

    let bitset_helper = if needs_bitset {
        quote! {
            fn bitset_contains(bitoff: u16, nbits: u32, data: &[u8], idx: i32) -> bool {
                let idx = idx - bitoff as i32;
                if idx < 0 || idx >= nbits as i32 {
                    return false;
                }
                let byte_idx = (idx >> 3) as usize;
                let bit_idx = (idx & 7) as u8;
                (data[byte_idx] & (1 << bit_idx)) != 0
            }
        }
    } else {
        quote! {}
    };

    // --- Per-tree scoring functions ---
    let tree_fns: Vec<TokenStream> = forest
        .trees
        .iter()
        .enumerate()
        .map(|(i, tree)| {
            let fn_name = format_ident!("tree_{}", i);
            let body = compile_node(&tree.root);
            quote! {
                #[inline(always)]
                fn #fn_name(features: &[f32]) -> f32 {
                    #body
                }
            }
        })
        .collect();

    // --- Softmax (multiclass) path: different aggregation and return type ---
    if let PostTransform::Softmax { n_classes } = &forest.post_transform {
        let n_classes = *n_classes;
        anyhow::ensure!(
            n_classes >= 2,
            "Softmax requires at least 2 classes, got {}",
            n_classes
        );
        anyhow::ensure!(
            forest.trees.len() % n_classes == 0,
            "Tree count ({}) must be divisible by n_classes ({}) for softmax",
            forest.trees.len(),
            n_classes
        );

        let output = build_softmax_model(forest, n_classes, &bitset_helper, &tree_fns)?;
        return Ok(output.to_string());
    }

    // --- Aggregation expression (f64 throughout for precision) ---
    let tree_calls: Vec<TokenStream> = forest
        .trees
        .iter()
        .enumerate()
        .map(|(i, tree)| {
            let fn_name = format_ident!("tree_{}", i);
            let w = tree.weight as f64;
            quote! { Self::#fn_name(features) as f64 * #w }
        })
        .collect();

    let aggregation_expr = match &forest.aggregation {
        AggregationKind::Sum => {
            let base = forest.base_score;
            quote! { #base + #(#tree_calls)+* }
        }
        AggregationKind::Average => {
            let n = forest.trees.len() as f64;
            quote! { (#(#tree_calls)+*) / #n }
        }
    };

    // --- Post-transform expression ---
    let post_transform_expr = match &forest.post_transform {
        PostTransform::Identity => quote! { raw as f32 },
        PostTransform::Logit => {
            quote! { (1.0f64 / (1.0f64 + (-raw).exp())) as f32 }
        }
        PostTransform::Log => {
            quote! { raw.exp() as f32 }
        }
        PostTransform::Softmax { .. } => unreachable!("handled above"),
    };

    // --- Assemble ---
    let output = quote! {
        /// Auto-generated by bonsai.
        /// Do not edit manually.
        #bitset_helper

        pub struct Model;

        impl Model {
            pub fn predict(&self, features: &[f32]) -> f32 {
                let raw: f64 = #aggregation_expr;
                #post_transform_expr
            }

            #(#tree_fns)*
        }
    };

    Ok(output.to_string())
}

// ---------------------------------------------------------------------------
// Node compilation
// ---------------------------------------------------------------------------

/// Recursively compile an IR node into a token stream of nested if/else blocks.
///
/// Convention: left_child is taken when the split condition is TRUE.
/// NaN routing is folded into the condition based on MissingDirection.
fn compile_node(node: &Node) -> TokenStream {
    match node {
        Node::Leaf { value } => {
            let v = *value;
            quote! { #v }
        }

        Node::Split {
            feature_idx,
            split,
            left_child,
            right_child,
            missing_direction,
        } => {
            let fi = *feature_idx;
            let left_code = compile_node(left_child);
            let right_code = compile_node(right_child);

            // Build the "go left" condition, incorporating NaN routing.
            //
            // MissingDirection::Left  → NaN goes left  → left_cond = is_nan  OR  cmp
            // MissingDirection::Right → NaN goes right → left_cond = !is_nan AND cmp
            // NaVsRest: splits solely on NaN-ness, NaN goes right
            let left_cond = match (missing_direction, split) {
                // NaVsRest nodes split only on NaN, threshold is unused (set to NAN)
                (MissingDirection::NaVsRest, _) => {
                    quote! { !val.is_nan() }
                }

                (_, SplitKind::Numeric { threshold, operator }) => {
                    let th = *threshold;
                    let cmp = match operator {
                        Operator::LessThan => quote! { val < #th },
                        Operator::LessOrEqual => quote! { val <= #th },
                        Operator::GreaterThan => quote! { val > #th },
                        Operator::GreaterOrEqual => quote! { val >= #th },
                        Operator::Equal => quote! { val == #th },
                        Operator::NotEqual => quote! { val != #th },
                    };

                    match missing_direction {
                        MissingDirection::Left => {
                            quote! { val.is_nan() || (#cmp) }
                        }
                        _ => {
                            // Right, None
                            quote! { !val.is_nan() && (#cmp) }
                        }
                    }
                }

                (_, SplitKind::Categorical { bitoff, nbits, data }) => {
                    let bo = *bitoff;
                    let nb = *nbits;
                    let bytes = data.clone();

                    let membership = quote! {
                        bitset_contains(#bo, #nb, &[#(#bytes),*], val as i32)
                    };

                    // In H2O MOJO: if value is IN bitset → RIGHT child, NOT IN bitset → LEFT child
                    // So we negate the membership test for the left condition
                    match missing_direction {
                        MissingDirection::Left => {
                            quote! { val.is_nan() || !#membership }
                        }
                        _ => {
                            quote! { !val.is_nan() && !#membership }
                        }
                    }
                }
            };

            // Wrap in a block so that `val` bindings at different tree depths
            // each live in their own scope and shadow cleanly.
            quote! {
                {
                    let val = features[#fi];
                    if #left_cond {
                        #left_code
                    } else {
                        #right_code
                    }
                }
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Softmax (multiclass) codegen
// ---------------------------------------------------------------------------

/// Generate the Model struct for a multiclass softmax forest.
///
/// Trees are assigned round-robin to classes: tree i → class (i % n_classes).
/// The predict_proba method returns a Vec<f32> of length n_classes.
fn build_softmax_model(
    forest: &Forest,
    n_classes: usize,
    bitset_helper: &TokenStream,
    tree_fns: &[TokenStream],
) -> Result<TokenStream> {
    let base = forest.base_score;

    // Build per-class raw score expressions
    let raw_decls: Vec<TokenStream> = (0..n_classes)
        .map(|c| {
            let raw_var = format_ident!("raw_{}", c);
            // Trees for class c: indices c, c+n_classes, c+2*n_classes, ...
            let terms: Vec<TokenStream> = forest
                .trees
                .iter()
                .enumerate()
                .filter(|(i, _)| i % n_classes == c)
                .map(|(i, tree)| {
                    let fn_name = format_ident!("tree_{}", i);
                    let w = tree.weight as f64;
                    quote! { Self::#fn_name(features) as f64 * #w }
                })
                .collect();

            match forest.aggregation {
                AggregationKind::Sum => {
                    quote! { let #raw_var: f64 = #base + #(#terms)+*; }
                }
                AggregationKind::Average => {
                    let n = terms.len() as f64;
                    quote! { let #raw_var: f64 = (#(#terms)+*) / #n; }
                }
            }
        })
        .collect();

    // max_raw for numerical stability
    let raw_vars: Vec<_> = (0..n_classes)
        .map(|c| format_ident!("raw_{}", c))
        .collect();
    let max_expr = raw_vars
        .iter()
        .skip(1)
        .fold(quote! { #(#raw_vars)* }, |acc, v| quote! { #acc.max(#v) });
    let max_decl = quote! { let max_raw: f64 = #max_expr; };

    // exp terms
    let exp_vars: Vec<_> = (0..n_classes)
        .map(|c| format_ident!("e_{}", c))
        .collect();
    let exp_decls: Vec<TokenStream> = raw_vars
        .iter()
        .zip(exp_vars.iter())
        .map(|(r, e)| quote! { let #e: f64 = (#r - max_raw).exp(); })
        .collect();

    // sum of exps
    let sum_decl = quote! { let sum_e: f64 = #(#exp_vars)+*; };

    // Output vec
    let prob_items: Vec<TokenStream> = exp_vars
        .iter()
        .map(|e| quote! { (#e / sum_e) as f32 })
        .collect();

    Ok(quote! {
        /// Auto-generated by bonsai.
        /// Do not edit manually.
        #bitset_helper

        pub struct Model;

        impl Model {
            pub fn predict_proba(&self, features: &[f32]) -> Vec<f32> {
                #(#raw_decls)*
                #max_decl
                #(#exp_decls)*
                #sum_decl
                vec![#(#prob_items),*]
            }

            #(#tree_fns)*
        }
    })
}

/// Walk the tree to check if any categorical split is present.
fn has_categorical(node: &Node) -> bool {
    match node {
        Node::Leaf { .. } => false,
        Node::Split {
            split,
            left_child,
            right_child,
            ..
        } => {
            matches!(split, SplitKind::Categorical { .. })
                || has_categorical(left_child)
                || has_categorical(right_child)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::*;

    fn leaf(v: f32) -> Node {
        Node::Leaf { value: v }
    }

    fn simple_split(fi: usize, th: f32, left: Node, right: Node) -> Node {
        Node::Split {
            feature_idx: fi,
            split: SplitKind::Numeric {
                threshold: th,
                operator: Operator::LessThan,
            },
            left_child: Box::new(left),
            right_child: Box::new(right),
            missing_direction: MissingDirection::Right,
        }
    }

    fn make_tree(root: Node) -> Tree {
        Tree { root, weight: 1.0 }
    }

    #[test]
    fn test_generate_regression_identity() {
        let forest = Forest {
            trees: vec![make_tree(simple_split(0, 0.5, leaf(1.0), leaf(-1.0)))],
            base_score: 0.0,
            aggregation: AggregationKind::Sum,
            post_transform: PostTransform::Identity,
        };
        let code = generate(&forest).unwrap();
        assert!(code.contains("pub fn predict"));
        assert!(code.contains("raw as f32"));
        assert!(!code.contains("predict_proba"));
    }

    #[test]
    fn test_generate_binary_logit() {
        let forest = Forest {
            trees: vec![make_tree(leaf(0.5))],
            base_score: 0.0,
            aggregation: AggregationKind::Sum,
            post_transform: PostTransform::Logit,
        };
        let code = generate(&forest).unwrap();
        assert!(code.contains("pub fn predict"));
        assert!(code.contains("exp"));
        assert!(!code.contains("predict_proba"));
    }

    #[test]
    fn test_generate_multiclass_softmax_3_classes() {
        // 6 trees, 3 classes: tree 0,3 → class 0; tree 1,4 → class 1; tree 2,5 → class 2
        let trees: Vec<Tree> = (0..6)
            .map(|i| make_tree(leaf(i as f32 * 0.1)))
            .collect();
        let forest = Forest {
            trees,
            base_score: 0.0,
            aggregation: AggregationKind::Sum,
            post_transform: PostTransform::Softmax { n_classes: 3 },
        };
        let code = generate(&forest).unwrap();

        assert!(code.contains("predict_proba"), "should generate predict_proba");
        assert!(!code.contains("pub fn predict("), "should NOT generate predict");
        assert!(code.contains("Vec < f32 >"), "return type should be Vec<f32>");
        assert!(code.contains("max_raw"), "should include numerical stability max");
        assert!(code.contains("sum_e"), "should include softmax denominator");
        // tree_0 and tree_3 both go to class 0
        assert!(code.contains("raw_0"), "class 0 raw score");
        assert!(code.contains("raw_1"), "class 1 raw score");
        assert!(code.contains("raw_2"), "class 2 raw score");
    }

    #[test]
    fn test_generate_softmax_rejects_odd_tree_count() {
        // 5 trees can't be divided into 3 classes
        let trees: Vec<Tree> = (0..5).map(|_| make_tree(leaf(0.0))).collect();
        let forest = Forest {
            trees,
            base_score: 0.0,
            aggregation: AggregationKind::Sum,
            post_transform: PostTransform::Softmax { n_classes: 3 },
        };
        assert!(generate(&forest).is_err(), "should error on indivisible tree count");
    }

    #[test]
    fn test_generate_no_bitset_without_categoricals() {
        let forest = Forest {
            trees: vec![make_tree(leaf(1.0))],
            base_score: 0.0,
            aggregation: AggregationKind::Sum,
            post_transform: PostTransform::Identity,
        };
        let code = generate(&forest).unwrap();
        assert!(!code.contains("bitset_contains"));
    }
}
