use crate::ir::{AggregationKind, Forest, MissingDirection, Node, Operator, PostTransform, SplitKind};
use anyhow::Result;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

/// Generate a standalone Rust source file from the given forest.
///
/// The output is a single module containing:
/// - A `bitset_contains` helper (only if categorical splits are present)
/// - A `Model` unit struct
/// - `Model::predict(&self, features: &[f32]) -> f32`
/// - One `#[inline(always)]` tree function per tree in the forest
pub fn generate(forest: &Forest) -> Result<String> {
    if forest.trees.is_empty() {
        anyhow::bail!("Cannot generate code for an empty forest (0 trees).");
    }

    // --- Conditional: bitset helper (emitted once at module scope) ---
    let needs_bitset = forest.trees.iter().any(|t| has_categorical(&t.root));

    let bitset_helper = if needs_bitset {
        quote! {
            fn bitset_contains(bitoff: u16, nbits: u32, data: &[u8], idx: i32) -> bool {
                let idx = idx - bitoff as i32;
                if idx < 0 || idx >= nbits as i32 {
                    return false;
                }
                let byte_idx = (idx >> 3) as usize;
                let bit_idx = (idx & 7) as u8;
                (data[byte_idx] & (1 << bit_idx)) != 0
            }
        }
    } else {
        quote! {}
    };

    // --- Per-tree scoring functions ---
    let tree_fns: Vec<TokenStream> = forest
        .trees
        .iter()
        .enumerate()
        .map(|(i, tree)| {
            let fn_name = format_ident!("tree_{}", i);
            let body = compile_node(&tree.root);
            quote! {
                #[inline(always)]
                fn #fn_name(features: &[f32]) -> f32 {
                    #body
                }
            }
        })
        .collect();

    // --- Aggregation expression (f64 throughout for precision) ---
    let tree_calls: Vec<TokenStream> = forest
        .trees
        .iter()
        .enumerate()
        .map(|(i, tree)| {
            let fn_name = format_ident!("tree_{}", i);
            let w = tree.weight as f64;
            quote! { Self::#fn_name(features) as f64 * #w }
        })
        .collect();

    let aggregation_expr = match &forest.aggregation {
        AggregationKind::Sum => {
            let base = forest.base_score;
            quote! { #base + #(#tree_calls)+* }
        }
        AggregationKind::Average => {
            let n = forest.trees.len() as f64;
            quote! { (#(#tree_calls)+*) / #n }
        }
    };

    // --- Post-transform expression ---
    let post_transform_expr = match &forest.post_transform {
        PostTransform::Identity => quote! { raw as f32 },
        PostTransform::Logit => {
            quote! { (1.0f64 / (1.0f64 + (-raw).exp())) as f32 }
        }
        PostTransform::Log => {
            quote! { raw.exp() as f32 }
        }
    };

    // --- Assemble ---
    let output = quote! {
        /// Auto-generated by bonsai.
        /// Do not edit manually.
        #bitset_helper

        pub struct Model;

        impl Model {
            pub fn predict(&self, features: &[f32]) -> f32 {
                let raw: f64 = #aggregation_expr;
                #post_transform_expr
            }

            #(#tree_fns)*
        }
    };

    Ok(output.to_string())
}

// ---------------------------------------------------------------------------
// Node compilation
// ---------------------------------------------------------------------------

/// Recursively compile an IR node into a token stream of nested if/else blocks.
///
/// Convention: left_child is taken when the split condition is TRUE.
/// NaN routing is folded into the condition based on MissingDirection.
fn compile_node(node: &Node) -> TokenStream {
    match node {
        Node::Leaf { value } => {
            let v = *value;
            quote! { #v }
        }

        Node::Split {
            feature_idx,
            split,
            left_child,
            right_child,
            missing_direction,
        } => {
            let fi = *feature_idx;
            let left_code = compile_node(left_child);
            let right_code = compile_node(right_child);

            // Build the "go left" condition, incorporating NaN routing.
            //
            // MissingDirection::Left  → NaN goes left  → left_cond = is_nan  OR  cmp
            // MissingDirection::Right → NaN goes right → left_cond = !is_nan AND cmp
            // NaVsRest: splits solely on NaN-ness, NaN goes right
            let left_cond = match (missing_direction, split) {
                // NaVsRest nodes split only on NaN, threshold is unused (set to NAN)
                (MissingDirection::NaVsRest, _) => {
                    quote! { !val.is_nan() }
                }

                (_, SplitKind::Numeric { threshold, operator }) => {
                    let th = *threshold;
                    let cmp = match operator {
                        Operator::LessThan => quote! { val < #th },
                        Operator::LessOrEqual => quote! { val <= #th },
                        Operator::GreaterThan => quote! { val > #th },
                        Operator::GreaterOrEqual => quote! { val >= #th },
                        Operator::Equal => quote! { val == #th },
                        Operator::NotEqual => quote! { val != #th },
                    };

                    match missing_direction {
                        MissingDirection::Left => {
                            quote! { val.is_nan() || (#cmp) }
                        }
                        _ => {
                            // Right, None
                            quote! { !val.is_nan() && (#cmp) }
                        }
                    }
                }

                (_, SplitKind::Categorical { bitoff, nbits, data }) => {
                    let bo = *bitoff;
                    let nb = *nbits;
                    let bytes = data.clone();

                    let membership = quote! {
                        bitset_contains(#bo, #nb, &[#(#bytes),*], val as i32)
                    };

                    // In H2O MOJO: if value is IN bitset → RIGHT child, NOT IN bitset → LEFT child
                    // So we negate the membership test for the left condition
                    match missing_direction {
                        MissingDirection::Left => {
                            quote! { val.is_nan() || !#membership }
                        }
                        _ => {
                            quote! { !val.is_nan() && !#membership }
                        }
                    }
                }
            };

            // Wrap in a block so that `val` bindings at different tree depths
            // each live in their own scope and shadow cleanly.
            quote! {
                {
                    let val = features[#fi];
                    if #left_cond {
                        #left_code
                    } else {
                        #right_code
                    }
                }
            }
        }
    }
}

/// Walk the tree to check if any categorical split is present.
fn has_categorical(node: &Node) -> bool {
    match node {
        Node::Leaf { .. } => false,
        Node::Split {
            split,
            left_child,
            right_child,
            ..
        } => {
            matches!(split, SplitKind::Categorical { .. })
                || has_categorical(left_child)
                || has_categorical(right_child)
        }
    }
}
